### ISSUE TITLE
Panic calling verify

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-bls-sigs#5]
Likely caused by passing in bad parameters, but we should avoid panicking if we can.

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: UnexpectedCompressionMode', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
fatal runtime error: failed to initiate panic, error 5
SIGABRT: abort
PC=0x7fb63a565e97 m=19 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7fb63a565e97
stack: frame={sp:0x7fb5d51f6310, fp:0x0} stack=[0x7fb5d49f6ec8,0x7fb5d51f6ac8)
00007fb5d51f6210:  00007fb5d51f6578  00007fb63ab412cc 
00007fb5d51f6220:  0000000000000000  0000000000000001 
00007fb5d51f6230:  0000000000000001  00007fb63ab41270 
00007fb5d51f6240:  00007fb63ab440e0  0000000000ec0af5 
00007fb5d51f6250:  0000000000000000  00007fb63ab412cc 
00007fb5d51f6260:  0000000000000000  0000000000000001 
00007fb5d51f6270:  0000000000000001  00007fb5d51f64a8 
00007fb5d51f6280:  000000000272a2e8  00007fb5d51f6320 
00007fb5d51f6290:  00007fb5d51f65d8  0000000000000001 
00007fb5d51f62a0:  0000000000000000  0000000000ec16eb 
00007fb5d51f62b0:  000000000272a2e8  00007fb5d51f6320 
00007fb5d51f62c0:  00007fb5d51f6503  0000000000000001 
00007fb5d51f62d0:  0000000000000001  0000000000f0af31 
00007fb5d51f62e0:  0000000000000000  0000000000ec16eb 
00007fb5d51f62f0:  0000000000000000  0000000000000000 
00007fb5d51f6300:  00007fb5d51f6503  35007fb5d51f6580 
00007fb5d51f6310: <0000000000000000  0000000000efcbcc 
00007fb5d51f6320:  0000000000000000  0000000000000000 
00007fb5d51f6330:  0000000000000000  00007fb63ab412cc 
00007fb5d51f6340:  00007fb5d51f64a8  0000000000000001 
00007fb5d51f6350:  0000000000000001  00007fb63ab41270 
00007fb5d51f6360:  00007fb63ab440e0  0000000000ec0af5 
00007fb5d51f6370:  0000002000000000  00007fb5d51f6a03 
00007fb5d51f6380:  0000000000000000  0000000000000001 
00007fb5d51f6390:  fffffffe7fffffff  ffffffffffffffff 
00007fb5d51f63a0:  ffffffffffffffff  ffffffffffffffff 
00007fb5d51f63b0:  ffffffffffffffff  ffffffffffffffff 
00007fb5d51f63c0:  ffffffffffffffff  ffffffffffffffff 
00007fb5d51f63d0:  ffffffffffffffff  ffffffffffffffff 
00007fb5d51f63e0:  ffffffffffffffff  ffffffffffffffff 
00007fb5d51f63f0:  ffffffffffffffff  ffffffffffffffff 
00007fb5d51f6400:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0x7fb63a565e97
stack: frame={sp:0x7fb5d51f6310, fp:0x0} stack=[0x7fb5d49f6ec8,0x7fb5d51f6ac8)
00007fb5d51f6210:  00007fb5d51f6578  00007fb63ab412cc 
00007fb5d51f6220:  0000000000000000  0000000000000001 
00007fb5d51f6230:  0000000000000001  00007fb63ab41270 
00007fb5d51f6240:  00007fb63ab440e0  0000000000ec0af5 
00007fb5d51f6250:  0000000000000000  00007fb63ab412cc 
00007fb5d51f6260:  0000000000000000  0000000000000001 
00007fb5d51f6270:  0000000000000001  00007fb5d51f64a8 
00007fb5d51f6280:  000000000272a2e8  00007fb5d51f6320 
00007fb5d51f6290:  00007fb5d51f65d8  0000000000000001 
00007fb5d51f62a0:  0000000000000000  0000000000ec16eb 
00007fb5d51f62b0:  000000000272a2e8  00007fb5d51f6320 
00007fb5d51f62c0:  00007fb5d51f6503  0000000000000001 
00007fb5d51f62d0:  0000000000000001  0000000000f0af31 
00007fb5d51f62e0:  0000000000000000  0000000000ec16eb 
00007fb5d51f62f0:  0000000000000000  0000000000000000 
00007fb5d51f6300:  00007fb5d51f6503  35007fb5d51f6580 
00007fb5d51f6310: <0000000000000000  0000000000efcbcc 
00007fb5d51f6320:  0000000000000000  0000000000000000 
00007fb5d51f6330:  0000000000000000  00007fb63ab412cc 
00007fb5d51f6340:  00007fb5d51f64a8  0000000000000001 
00007fb5d51f6350:  0000000000000001  00007fb63ab41270 
00007fb5d51f6360:  00007fb63ab440e0  0000000000ec0af5 
00007fb5d51f6370:  0000002000000000  00007fb5d51f6a03 
00007fb5d51f6380:  0000000000000000  0000000000000001 
00007fb5d51f6390:  fffffffe7fffffff  ffffffffffffffff 
00007fb5d51f63a0:  ffffffffffffffff  ffffffffffffffff 
00007fb5d51f63b0:  ffffffffffffffff  ffffffffffffffff 
00007fb5d51f63c0:  ffffffffffffffff  ffffffffffffffff 
00007fb5d51f63d0:  ffffffffffffffff  ffffffffffffffff 
00007fb5d51f63e0:  ffffffffffffffff  ffffffffffffffff 
00007fb5d51f63f0:  ffffffffffffffff  ffffffffffffffff 
00007fb5d51f6400:  ffffffffffffffff  ffffffffffffffff 

goroutine 659 [syscall]:
runtime.cgocall(0xe30430, 0xc000aad328, 0x17a5800)
	/home/why/go/src/runtime/cgocall.go:128 +0x5b fp=0xc000aad2f8 sp=0xc000aad2c0 pc=0x4dbf0b
github.com/filecoin-project/go-bls-sigs._Cfunc_verify(0x7fb5a8000b20, 0x7fb5a8000b90, 0x60, 0x7fb5a8000c00, 0x30, 0x0)
	_cgo_gotypes.go:283 +0x4e fp=0xc000aad328 sp=0xc000aad2f8 pc=0x9808ce
github.com/filecoin-project/go-bls-sigs.Verify(0x7272612065656576, 0x666666652072, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/why/code/go-lotus/extern/go-bls-sigs/bls.go:61 +0x41f fp=0xc000aad4e0 sp=0xc000aad328 pc=0x980fdf
github.com/filecoin-project/go-lotus/chain/types.(*Signature).Verify(0xc000aad808, 0xc00024a400, 0x31, 0xc0006f1c00, 0x11, 0x11, 0xc000aad830, 0xa0b1da)
	/home/why/code/go-lotus/chain/types/signature.go:94 +0x68b fp=0xc000aad780 sp=0xc000aad4e0 pc=0x99375b
github.com/filecoin-project/go-lotus/chain.(*Syncer).validateTickets(0xc0005a3ae0, 0x1b44be0, 0xc00003c100, 0xc00024a400, 0x31, 0xc000374718, 0x1, 0x1, 0xc00036f980, 0x0, ...)
	/home/why/code/go-lotus/chain/sync.go:356 +0x132 fp=0xc000aad840 sp=0xc000aad780 pc=0xa0ae42
github.com/filecoin-project/go-lotus/chain.(*Syncer).ValidateBlock(0xc0005a3ae0, 0x1b44be0, 0xc00003c100, 0xc00036e680, 0x0, 0x0)
	/home/why/code/go-lotus/chain/sync.go:419 +0x49e fp=0xc000aada68 sp=0xc000aad840 pc=0xa0b85e
github.com/filecoin-project/go-lotus/chain.(*Syncer).ValidateTipSet(0xc0005a3ae0, 0x1b44be0, 0xc00003c100, 0xc0004b5c80, 0xc000a15b50, 0x2)
	/home/why/code/go-lotus/chain/sync.go:309 +0xb8 fp=0xc000aadac0 sp=0xc000aada68 pc=0xa0a968
github.com/filecoin-project/go-lotus/chain.(*Syncer).syncMessagesAndCheckState.func1(0xc0004b5c80, 0xc000401840, 0x0)
	/home/why/code/go-lotus/chain/sync.go:535 +0x131 fp=0xc000aadb80 sp=0xc000aadac0 pc=0xa0fe01
github.com/filecoin-project/go-lotus/chain.(*Syncer).iterFullTipsets(0xc0005a3ae0, 0xc0001dc200, 0x32, 0x40, 0xc000aade28, 0x1b44f60, 0xc00001a690)
	/home/why/code/go-lotus/chain/sync.go:593 +0x255 fp=0xc000aaddf0 sp=0xc000aadb80 pc=0xa0d135
github.com/filecoin-project/go-lotus/chain.(*Syncer).syncMessagesAndCheckState(0xc0005a3ae0, 0xc0001dc200, 0x32, 0x40, 0x32, 0x40)
	/home/why/code/go-lotus/chain/sync.go:533 +0x6c fp=0xc000aade48 sp=0xc000aaddf0 pc=0xa0ceac
github.com/filecoin-project/go-lotus/chain.(*Syncer).collectChain(0xc0005a3ae0, 0xc00048fa00, 0xc0005a3a00, 0x0)
	/home/why/code/go-lotus/chain/sync.go:648 +0x1eb fp=0xc000aadef8 sp=0xc000aade48 pc=0xa0e45b
github.com/filecoin-project/go-lotus/chain.(*Syncer).Sync(0xc0005a3ae0, 0xc00048fa00, 0x0, 0x0)
	/home/why/code/go-lotus/chain/sync.go:291 +0xc6 fp=0xc000aadf60 sp=0xc000aadef8 pc=0xa0a736
github.com/filecoin-project/go-lotus/chain.(*Syncer).InformNewHead.func1(0xc0005a3ae0, 0xc00048fa00)
	/home/why/code/go-lotus/chain/sync.go:105 +0x39 fp=0xc000aadfd0 sp=0xc000aadf60 pc=0xa0fc39
runtime.goexit()
	/home/why/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000aadfd8 sp=0xc000aadfd0 pc=0x536061
created by github.com/filecoin-project/go-lotus/chain.(*Syncer).InformNewHead
	/home/why/code/go-lotus/chain/sync.go:104 +0x143
```

**Comment by whyrusleeping** [comment]
oh yeah, i was passing the wrong bytes for the signature.

So, i'd expect verifying a bad signature to return an error saying bad signature or something

**Comment by dignifiedquire** [comment]
I guess you ran into: https://github.com/filecoin-project/bls-signatures/issues/6
